# Generated by Django 3.1.3 on 2022-03-21 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitiy',
            old_name='community',
            new_name='communities',
        ),
    ]
